import { defineConfig } from 'vitepress'
// `.vitepress/config.js`
import { withSidebar } from 'vitepress-sidebar';

const vitePressOptions = {
  // VitePress's options here...
  title: "NJUIS-Students",
  description: "A wiki for NJU-IS students.",
  // rewrites(id: string) {
  //   return id.replace(/(^|\/)\d+\-/g, '$1');
  // },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      // { text: 'Examples', link: '/markdown-examples' }
    ],

    // Sidebar will be generated by `vitepress-sidebar` plugin

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  }
};

const vitePressSidebarOptions = {
  // VitePress Sidebar's options here...
  // project docs folder (per plugin docs should be '/docs' if docs is under project root)
  documentRootPath: '/docs',
  collapsed: false,
  capitalizeFirst: true,
  // useTitleFromFrontmatter: true,
  // sortMenusOrderNumericallyFromTitle: true,
  sortMenusOrderByDescending: false,
  removePrefixAfterOrdering: true,
  prefixSeparator: '-',
  // enable debug printing to see generated sidebar in console
  debugPrint: true
  // useFolderTitleFromIndexFile: true
  // sortMenusByFrontmatterOrder: true,
  // frontmatterOrderDefaultValue: 999,
  // manualSortFileNameByPriority:  [
  //   "基础篇",
  //   "学习篇",
  //   "科研篇",
  //   "职场篇",
  //   "生活篇",
  //   "FAQ",
  //   "贡献篇"
  // ]
};


// https://vitepress.dev/reference/site-config
export default defineConfig(
  withSidebar(vitePressOptions, vitePressSidebarOptions)
)
